version: '3.8'

services:
    bot:
        container_name: get_anime_bot
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: on-failure
        env_file: .env
        depends_on:
            - db
            - db_migration
    db:
        image: postgres:14-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    db_migration:
        build: .
        restart: on-failure
        depends_on:
            - db
        env_file: .env
        command: sh -c "python -m alembic upgrade head"

volumes:
    postgres-data:
