version: '3.8'

services:
    bot:
        container_name: get_anime_bot_dev
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: on-failure
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
        depends_on:
            - db
        networks:
            - backend_dev
    db:
        container_name: get_anime_bot_db_dev
        image: postgres:14-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - backend_dev

volumes:
    postgres-data:

networks:
    backend_dev:
        name: get_anime_bot_backend_dev
        driver: bridge
