version: '3.8'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        stop_signal: SIGINT
        restart: "unless-stopped"
        volumes:
          - config.ini
