"""del column and rename column

Revision ID: 305e45dcec1a
Revises: 6a30db5069b7
Create Date: 2022-06-21 15:10:25.261145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305e45dcec1a'
down_revision = '6a30db5069b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'show_nsfw',
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )
    op.drop_column('users', 'can_check_nsfw')
    op.drop_column('users', 'hide_nsfw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hide_nsfw', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('can_check_nsfw', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'show_nsfw')
    # ### end Alembic commands ###
