"""rename column

Revision ID: 6a30db5069b7
Revises: bb5fefd450f1
Create Date: 2022-06-19 22:45:55.196069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a30db5069b7'
down_revision = 'bb5fefd450f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_constraint('media_source_fkey', 'media', type_='foreignkey')
    op.create_foreign_key(None, 'media', 'sources', ['source_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('media', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('source', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_foreign_key('media_source_fkey', 'media', 'sources', ['source'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('media', 'source_id')
    # ### end Alembic commands ###
