"""Add unique constraint to view

Revision ID: ea4780da43f5
Revises: 53cc2c59da45
Create Date: 2022-10-05 15:32:15.498251

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ea4780da43f5'
down_revision = '53cc2c59da45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'views', ['user_tg_id', 'media_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'views', type_='unique')  # type: ignore
    # ### end Alembic commands ###
